[tool.taskipy.tasks]
lint = "ruff check ."
pre_format = "ruff check --fix"
format = "ruff format ."
run = "fastapi de api/app.py"
pre_test = "task lint"
test = "pytest -s -x --cov=api -vv"
post_test = "coverage html"
